#ifndef BATCHPROCESS_GLOBAL_H
#define BATCHPROCESS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BATCHPROCESS_LIBRARY)
#  define BATCHPROCESSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BATCHPROCESSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BATCHPROCESS_GLOBAL_H
