#ifndef BATCHPROCESS_H
#define BATCHPROCESS_H


#define PIN_LENGTH 40.
#define PIN_POINT_SIZE 16.
#define PIN_DISTANCE_HALF 40.
#define PIN_DISTANCE PIN_DISTANCE_HALF * 2.
#define TASK_BODY_HEIGHT_MIN PIN_DISTANCE
#define TASK_BODY_WIDTH_MIN PIN_DISTANCE

#endif // BATCHPROCESS_H
